USE [HCvicna]
GO

/****** Object:  Table [dbo].[TabDokladyZbozi_EXT]    Script Date: 02.07.2025 13:34:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TabDokladyZbozi_EXT](
	[ID] [int] NOT NULL,
	[_Blokacenakupu] [bit] NULL,
	[_cislodl] [nvarchar](60) NULL,
	[_cislofa] [nvarchar](20) NULL,
	[_datum_uza] [datetime] NULL,
	[_uzavrel] [nvarchar](15) NULL,
	[_dtumvyporadani] [datetime] NULL,
	[_RAYBalitDle] [nvarchar](25) NULL,
	[_org_mark_fakt] [nvarchar](100) NULL,
	[_8dRepOde] [bit] NULL,
	[_8dRepDor] [bit] NULL,
	[_Hodnoceni_dodavky] [nvarchar](3) NULL,
	[_Poznamka] [nvarchar](255) NULL,
	[_Hodnoceni_dodavky2] [nvarchar](3) NULL,
	[_hodnoceni_dodavky3] [datetime] NULL,
	[_hodnoceni_dodavky4] [nvarchar](3) NULL,
	[_Hodnoceni_dodavky5] [nvarchar](3) NULL,
	[_hodnoceni_dodavky6] [bit] NULL,
	[_hodnoceni_dodavky7] [nvarchar](30) NULL,
	[_kumulaceAR] [bit] NULL,
	[_RedengeExpedicniPrikazNovy] [bit] NULL,
	[_ExpPrikazNovyDatum] [datetime] NULL,
	[_RedengeExpedicniPrikazZmena] [bit] NULL,
	[_ExpPrikazZmenaDatum] [datetime] NULL,
	[_RedengeExpedicniPrikazPotvrz] [bit] NULL,
	[_ExpPrikazPotvrzeniDatum] [datetime] NULL,
	[_InterniSdeleni] [text] NULL,
	[_ARneopr] [nvarchar](11) NULL,
	[_Redenge_Shop_Note] [text] NULL,
	[_ISDOCGUID] [varchar](36) NULL,
	[_ZvprSpok] [bit] NULL,
	[_ZvszNespok] [bit] NULL,
	[_KomePr] [text] NULL,
	[_zvlastnipozadavek] [bit] NULL,
	[_offsety] [numeric](19, 6) NULL,
	[_blokace_platby] [bit] NULL,
	[_datum_od] [datetime] NULL,
	[_datum_do] [datetime] NULL,
	[_zamestnanec] [nvarchar](40) NULL,
	[_odblokovano] [datetime] NULL,
	[_poznamka_blokace] [text] NULL,
	[_dod_fak_vyfa] [nvarchar](30) NULL,
	[_Typ_Zakazky] [nvarchar](15) NULL,
	[_Datum_dalsiho_jednani] [datetime] NULL,
	[_Datum1_Kontaktu] [datetime] NULL,
	[_Forma] [nvarchar](15) NULL,
	[_AutorKontaktu] [nvarchar](10) NULL,
	[_Poznámka1_kontaktu] [nvarchar](250) NULL,
	[_Datum2_Kontaktu] [datetime] NULL,
	[_Forma2Kontaktu] [nvarchar](15) NULL,
	[_Autor2kontaktu] [nvarchar](20) NULL,
	[_Poznámka2kontaktu] [nvarchar](250) NULL,
	[_reach] [bit] NULL,
	[_rohs] [bit] NULL,
	[_imsd] [bit] NULL,
	[_RS_AutorRealizace] [nvarchar](128) NULL,
	[_stavbaIIIetapa] [bit] NULL,
	[_DBP] [bit] NULL,
	[_cislo_dobropisu] [numeric](19, 6) NULL,
	[_SD_SchvalovaniPozastaveno] [bit] NULL,
	[_Kvyskladneni] [bit] NULL,
	[_DatumExpEDI] [datetime] NULL,
	[_prislib_datum_uhrady] [datetime] NULL,
	[_EXT_DocCreatedByB2aDima] [bit] NULL,
	[_ZF_NEUHRAZENÉ] [bit] NULL,
	[_KodUmiProNaskl] [nvarchar](15) NULL,
	[_EXT_RS_doklad_ke_schvaleni] [bit] NULL,
	[_EXT_RS_termin_naceneni_kalkulace] [datetime] NULL,
	[_InfoProVK] [nvarchar](20) NULL,
	[_ISDOC_Extensions] [ntext] NULL,
	[_EXT_RS_jsd] [bit] NULL,
	[_EXT_RS_mrn] [nvarchar](30) NULL,
	[_EXT_RS_jsdPoznamka] [nvarchar](255) NULL,
	[_EXT_RS_path_attachements] [nvarchar](2000) NULL,
	[_EXT_RS_checked_BON] [bit] NULL,
	[_EXT_RS_exist_VDD] [bit] NULL,
	[_EXT_RS_print_formula] [int] NULL,
	[_EXT_RS_DateTakeOut] [datetime] NULL,
	[_EXT_RS_robot_cannot_realize] [bit] NULL,
	[_EXT_RS_robot_related_costs] [numeric](19, 6) NULL,
	[_EXT_RS_TechnologyOffer] [int] NULL,
	[_EXT_RS_DateConfirmationFrameOrder] [datetime] NULL,
	[_EXT_RS_DatumOdeslaniMailuDL] [datetime] NULL,
	[SystemRowVersionExt] [timestamp] NOT NULL,
	[SystemRowVersionExtText]  AS (CONVERT([nvarchar](16),CONVERT([binary](8),[SystemRowVersionExt]),(2))),
	[_EXT_RS_PlatformaPoptavky] [nvarchar](30) NULL,
	[_EXT_RS_DuvodZpomaleniExpedice] [nvarchar](30) NULL,
	[_Balikobot_PocetBaliku] [int] NULL,
	[_Balikobot_branch_id] [nvarchar](100) NULL,
	[_DatEskAR] [datetime] NULL,
	[_EXT_RS_IncomingDate] [datetime] NULL,
	[_EXT_RS_IDPrijemkyRS_SK] [int] NULL,
	[_EXT_RS_DatumOdeslaniMailuCN] [datetime] NULL,
	[_odsouhlasen8D] [datetime] NULL,
	[_EXT_RS_AvizoOVyzvednuti] [datetime] NULL,
	[_Balikobot_rec_id] [nvarchar](50) NULL,
	[_TiskPolNazev2] [bit] NULL,
	[_TiskPolNazev3] [bit] NULL,
	[_TiskPolNazev4] [bit] NULL,
	[_EXT_RS_PlanovaneUkonceniOperace] [datetime] NULL,
 CONSTRAINT [PK__TabDokladyZbozi_EXT__ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

