USE [HCvicna]
GO

/****** Object:  Table [dbo].[TabCisOrg_EXT]    Script Date: 02.07.2025 13:23:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TabCisOrg_EXT](
	[ID] [int] NOT NULL,
	[_SEGMENT_AKTIVIT] [nvarchar](30) NULL,
	[_kONKURENt] [bit] NULL,
	[_ZdrojKontaktu] [nvarchar](240) NULL,
	[_PusobeniKonkurence] [ntext] NULL,
	[_BalitDle] [nvarchar](50) NULL,
	[_Vyr] [bit] NULL,
	[_TypZakaznika] [nvarchar](20) NULL,
	[_PomocnyText] [nvarchar](255) NULL,
	[_CisloObchZas] [int] NULL,
	[_OrgSloz] [bit] NULL,
	[_poznamkaMarkInformace] [ntext] NULL,
	[_zpusobDopravy] [nvarchar](60) NULL,
	[_dodaciPodminky] [nvarchar](20) NULL,
	[_formaUhrady] [nvarchar](120) NULL,
	[_POZNAMKA] [nvarchar](30) NULL,
	[_odpovednaOsobaOdberatel] [nvarchar](30) NULL,
	[_rok_zjist_potreb] [bit] NULL,
	[_poznamka2009] [varchar](60) NULL,
	[_shop] [bit] NULL,
	[_vysledek_vstup_dot] [nvarchar](3) NULL,
	[_e_shop] [bit] NULL,
	[_datum_vlozeni] [datetime] NULL,
	[_poznamka_upresneni] [text] NULL,
	[_dat_vypln_dot] [datetime] NULL,
	[_fakturace_2004] [numeric](19, 6) NULL,
	[_fakturace_2005] [numeric](19, 6) NULL,
	[_fakturace_2006] [numeric](19, 6) NULL,
	[_fakturace_2007] [numeric](19, 6) NULL,
	[_fakturace_2008] [numeric](19, 6) NULL,
	[_fakturace_2009] [numeric](19, 6) NULL,
	[_fakturace_2010] [numeric](19, 6) NULL,
	[_fakturace_2011] [numeric](19, 6) NULL,
	[_fakturace_2012] [numeric](19, 6) NULL,
	[_analyza_stav] [nvarchar](20) NULL,
	[_fakturace_2003] [numeric](19, 6) NULL,
	[_Redenge_RedengeKit_Longitude] [float] NULL,
	[_Redenge_RedengeKit_Latitude] [float] NULL,
	[_Redenge_RedengeKit_GeocodeStatus] [varchar](30) NULL,
	[_potencial_nar_trzeb] [bit] NULL,
	[_e_fakturace] [bit] NULL,
	[_email] [nvarchar](100) NULL,
	[_nabidka_e_fakturace] [bit] NULL,
	[_souhlas_e_fakturace] [bit] NULL,
	[_platnost] [datetime] NULL,
	[_kalkulacni_skupina] [nvarchar](20) NULL,
	[_POZNAMKA_] [nvarchar](20) NULL,
	[_stav_dodavatele] [nvarchar](15) NULL,
	[_RAY_PuvodOrg_JOC] [int] NULL,
	[_RAY_PPMZa12MVyr_JOC] [int] NULL,
	[_RAY_PPMZa12MZb_JOC] [int] NULL,
	[_RAY_PPMZaObdVyr_JOC] [int] NULL,
	[_RAY_PPMZaObdZbo_JOC] [int] NULL,
	[_riziko] [ntext] NULL,
	[_druh_rizika] [nvarchar](255) NULL,
	[_typ_dodavatele] [nvarchar](20) NULL,
	[_vs_obch_podm] [nvarchar](10) NULL,
	[_vn_schvaleni] [bit] NULL,
	[_Creditcheck_ZaniklySub] [bit] NULL,
	[_Creditcheck_Stav] [int] NULL,
	[_Creditcheck_WebFree] [nvarchar](255) NULL,
	[_Creditcheck_WebFull] [nvarchar](255) NULL,
	[_Creditcheck_DatAktualizace] [datetime] NULL,
	[_rocni_plan_KJ] [nvarchar](30) NULL,
	[_kategorie_dodavatele] [nvarchar](30) NULL,
	[_kalkulacni_skupina_dosazena_rok] [nvarchar](5) NULL,
	[_kalkulacni_skupina_dosazena_2012] [nvarchar](5) NULL,
	[_nabidka_e_fakturace_pf] [bit] NULL,
	[_platnost_pf_od] [datetime] NULL,
	[_Creditcheck_Neupozornovat] [bit] NULL,
	[_ISDOC_ElPosAgreementRef] [varchar](255) NULL,
	[_fakturace_2013] [numeric](19, 6) NULL,
	[_nda] [bit] NULL,
	[_fakturace_2014] [numeric](19, 6) NULL,
	[_fakturace_2015] [numeric](19, 6) NULL,
	[_fakturace_2016] [numeric](19, 6) NULL,
	[_plantrzeb_2015] [int] NULL,
	[_kod_zakaznika] [nvarchar](20) NULL,
	[_Redenge_Discount_LastChangeDate] [datetime] NULL,
	[_Redenge_Discount_LastProcessDate] [datetime] NULL,
	[_Redenge_LastChangeDate] [datetime] NULL,
	[_Redenge_LastProcessDate] [datetime] NULL,
	[_Redenge_ProducerOrProvider] [bit] NULL,
	[_Creditcheck_IdCc] [int] NULL,
	[_Creditcheck_Datum_Zmeny] [datetime] NULL,
	[_popis_rizika] [ntext] NULL,
	[_backOffice] [nvarchar](20) NULL,
	[_kalkulacni_skupina_dosazena_2014] [nvarchar](7) NULL,
	[_kalkulacni_skupina_dosazena_2015] [nvarchar](5) NULL,
	[_plantrzeb_2016] [int] NULL,
	[_Plan2016A] [int] NULL,
	[_Plan2016A1] [int] NULL,
	[_Plan2016B] [int] NULL,
	[_Incoterms] [nvarchar](25) NULL,
	[_OrgTPV200] [nvarchar](20) NULL,
	[_OrgTPV100] [nvarchar](20) NULL,
	[_orgVU] [nvarchar](20) NULL,
	[_Plan2016EMA] [int] NULL,
	[_Plan2016MA] [int] NULL,
	[_Plan2016MP] [int] NULL,
	[_DL_Syst_C] [nvarchar](20) NULL,
	[_FormFai] [bit] NULL,
	[_FormOdch] [bit] NULL,
	[_DatumAuditu] [datetime] NULL,
	[_VysledekAuditu] [nvarchar](3) NULL,
	[_kalkSkupDistr] [nvarchar](20) NULL,
	[_CofCOK] [bit] NULL,
	[_EDIFV_NumMsg] [int] NULL,
	[_EDIFV_DirectoryMsg] [varchar](100) NULL,
	[_EDIFV_PrefixSouboru] [varchar](30) NULL,
	[_EDIFV_PriponaSouboru] [varchar](10) NULL,
	[_EDIOdetteID] [nvarchar](35) NULL,
	[_EDIIdentifikatorOdberatele] [nvarchar](35) NULL,
	[_OznacZboziZdroj] [int] NULL,
	[_OdstranitCRLF] [bit] NULL,
	[_PridatPozKNazvuZbozi] [bit] NULL,
	[_Plan2017A] [int] NULL,
	[_Plan2017A1] [int] NULL,
	[_Plan2017B] [int] NULL,
	[_Plan2017EMA] [int] NULL,
	[_Plan2017MA] [int] NULL,
	[_Plan2017MP] [int] NULL,
	[_PlanTrzeb2017] [int] NULL,
	[_TrzbaVH2016] [int] NULL,
	[_sen2017] [int] NULL,
	[_PlanMarze2017A] [int] NULL,
	[_Plan2017C] [int] NULL,
	[_sen2016] [int] NULL,
	[_fakturace_2017] [numeric](19, 6) NULL,
	[_fakturace_2018] [numeric](19, 6) NULL,
	[_PlanTrzeb2018] [int] NULL,
	[_dodziv] [bit] NULL,
	[_jineDokumenty] [bit] NULL,
	[_EXT_generovat_poradi] [bit] NULL,
	[_Plan2018A] [int] NULL,
	[_Plan2018A1] [int] NULL,
	[_Plan2018B] [int] NULL,
	[_Plan2018EMA] [int] NULL,
	[_PlanMarze2018A] [int] NULL,
	[_odpracHod2017] [int] NULL,
	[_CastkaNP] [numeric](19, 6) NULL,
	[_platnostSmlouvy] [datetime] NULL,
	[_fakturace_2019] [numeric](19, 6) NULL,
	[_fakturace_2020] [numeric](19, 6) NULL,
	[_fakturace_2021] [numeric](19, 6) NULL,
	[_ReachOdes] [datetime] NULL,
	[_ReachVrac] [bit] NULL,
	[_NdaPlatnost] [datetime] NULL,
	[_EXT_RS_packing_plan] [nvarchar](20) NULL,
	[_PlatDlPD] [datetime] NULL,
	[_EXT_RS_plan_trzeb_1Q_100] [int] NULL,
	[_EXT_RS_plan_trzeb_2Q_100] [int] NULL,
	[_EXT_RS_plan_trzeb_3Q_100] [int] NULL,
	[_EXT_RS_plan_trzeb_4Q_100] [int] NULL,
	[_fakturace_2022] [numeric](19, 6) NULL,
	[_fakturace_2023] [numeric](19, 6) NULL,
	[_fakturace_2024] [numeric](19, 6) NULL,
	[_fakturace_2025] [numeric](19, 6) NULL,
	[_fakturace_2026] [numeric](19, 6) NULL,
	[_EXT_PPMsupplier] [int] NULL,
	[_EXT_RS_platnost_QMS] [datetime] NULL,
	[_EXT_RS_special_certifikat_platnost] [datetime] NULL,
	[_EXT_RS_typ_certifikatu] [int] NULL,
	[_EXT_RS_segmentace] [nvarchar](30) NULL,
	[_VG_request] [bit] NULL,
	[_PlatAkred] [datetime] NULL,
	[_EXT_RS_prijem_realizuje_robot] [bit] NULL,
	[_ElekForm] [bit] NULL,
	[_EXT_RS_SendDeliveryNoteMail] [bit] NULL,
	[_FaiElektronicky] [bit] NULL,
	[_EXT_RS_forma_uhrady_IRPA] [nvarchar](30) NULL,
	[_EXT_RS_faktury_porizuje_robot] [bit] NULL,
	[SystemRowVersionExt] [timestamp] NOT NULL,
	[SystemRowVersionExtText]  AS (CONVERT([nvarchar](16),CONVERT([binary](8),[SystemRowVersionExt]),(2))),
	[_EXT_RS_PlanMarginsDistQ1] [int] NULL,
	[_EXT_RS_PlanTrzeb1QD] [int] NULL,
	[_EXT_RS_PlanTrzeb2QD] [int] NULL,
	[_EXT_RS_PlanTrzeb3QD] [int] NULL,
	[_EXT_RS_PlanTrzeb4QD] [int] NULL,
	[_odpovednaOsobaOdberatelD] [nvarchar](30) NULL,
	[_EXT_RS_PlatformaPoptavky] [nvarchar](30) NULL,
	[_EXT_RS_DuvodZpomaleniExpedice] [nvarchar](30) NULL,
	[_specialistaNakupV] [nvarchar](30) NULL,
	[_Balikobot_ZdrojMenaDobirky] [int] NULL,
	[_EXT_RS_GenerovanDotaznikDodavatele] [bit] NULL,
	[_EXT_RS_GenerovatKodex] [bit] NULL,
	[_EXT_RS_GenerovanySankceRusko] [bit] NULL,
	[_EXT_RS_ObchodniDohodaOd] [datetime] NULL,
	[_EXT_ObhodniDohodaDo] [datetime] NULL,
	[_EXT_RS_PlanMargins25DistQ1] [int] NULL,
	[_EXT_RS_PlanMargins25DistQ2] [int] NULL,
	[_EXT_RS_PlanMargins25DistQ3] [int] NULL,
	[_EXT_RS_PlanMargins25DistQ4] [int] NULL,
	[_EXT_RS_PlanTrzeb1Q25D] [int] NULL,
	[_EXT_RS_PlanTrzeb2Q25D] [int] NULL,
	[_EXT_RS_PlanTrzeb3Q25D] [int] NULL,
	[_EXT_RS_PlanTrzeb4Q25D] [int] NULL,
	[_EXT_RS_PlanTrzeb1Q25K] [int] NULL,
	[_EXT_RS_PlanTrzeb2Q25K] [int] NULL,
	[_EXT_RS_PlanTrzeb3Q25K] [int] NULL,
	[_EXT_RS_PlanTrzeb4Q25K] [int] NULL,
	[_EXT_RS_PlanTrzeb1Q25B] [int] NULL,
	[_EXT_RS_PlanTrzeb2Q25B] [int] NULL,
	[_EXT_RS_PlanTrzeb3Q25B] [int] NULL,
	[_EXT_RS_PlanTrzeb4Q25B] [int] NULL,
	[_EXT_RS_ProvereniSankcniMapa] [datetime] NULL,
	[_EXT_RS_DatumOdeslaniMailuCN2] [datetime] NULL,
	[_EXT_RS_Vyrobce] [bit] NULL,
	[_EXT_RS_AkceptaceBezDokladu] [bit] NULL,
	[_EXT_RS_DatumOdeslaniMailuCNProdej] [datetime] NULL,
	[_EXT_RS_GenerovanySankceCina] [bit] NULL,
 CONSTRAINT [PK__TabCisOrg_EXT__ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

