USE [RayService]
GO

/****** Object:  StoredProcedure [dbo].[hpx_RS_OpravaRadyVPOUTMFGORDER]    Script Date: 30.06.2025 8:24:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[hpx_RS_OpravaRadyVPOUTMFGORDER]
AS
SET NOCOUNT ON;
--SELECT prop.ID, prop.MFG_ORDER_ID, prop.STRING_VALUE, prop2.STRING_VALUE
UPDATE prop SET prop.STRING_VALUE='100'
FROM GTabAPSLogis_OUT_MANUFACTURINGORDER mor
LEFT OUTER JOIN GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY prop ON prop.MFG_ORDER_ID=mor.MFG_ORDER_ID AND prop.ATTRIBUTE_NAME LIKE N'RAY_RadaVP'
LEFT OUTER JOIN GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY prop2 ON prop2.MFG_ORDER_ID=mor.MFG_ORDER_ID AND prop2.ATTRIBUTE_NAME LIKE N'RAY_SkupinaPlanu'
WHERE ((prop.STRING_VALUE NOT LIKE N'100' OR prop.STRING_VALUE NOT LIKE N'803'))AND(prop2.STRING_VALUE LIKE N'%P100%')AND(mor.Generovano=0)AND(mor.MFG_ORDER_ID LIKE N'MFG%')
--MŽ, 11.2.2025 na poradě LPP nová změna
UPDATE prop SET prop.STRING_VALUE='050'
FROM GTabAPSLogis_OUT_MANUFACTURINGORDER mor
LEFT OUTER JOIN GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY prop ON prop.MFG_ORDER_ID=mor.MFG_ORDER_ID AND prop.ATTRIBUTE_NAME LIKE N'RAY_RadaVP'
LEFT OUTER JOIN GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY prop2 ON prop2.MFG_ORDER_ID=mor.MFG_ORDER_ID AND prop2.ATTRIBUTE_NAME LIKE N'RAY_SkupinaPlanu'
WHERE ((prop.STRING_VALUE NOT LIKE N'050' OR prop.STRING_VALUE NOT LIKE N'803'))AND(prop2.STRING_VALUE LIKE N'%XXX%')AND(mor.Generovano=0)AND(mor.MFG_ORDER_ID LIKE N'MFG%')

GO

