USE [RayService]
GO

/****** Object:  View [dbo].[hvw_B0E95F34074448E1B22ADFF2AA002BF7]    Script Date: 03.07.2025 13:35:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_B0E95F34074448E1B22ADFF2AA002BF7] AS SELECT
Datum
,DATEPART(DAY,Datum) AS Datum_D
,DATEPART(MONTH,Datum) AS Datum_M
,DATEPART(QUARTER,Datum) AS Datum_Q
,DATEPART(YEAR,Datum) AS Datum_Y
,DATEPART(WEEK,Datum) AS Datum_T
,DATEPART(ISO_WEEK,Datum) AS Datum_TISO
,Mnozstvi
,Autor
FROM RayService..TabRSPlanLaser WITH(NOLOCK)
GO

