USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_IN_PLANNEDBATCH]    Script Date: 03.07.2025 13:03:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_IN_PLANNEDBATCH] AS SELECT 
  PLANNED_BATCH_ID=X.PLANNED_BATCH_ID, 
  RESOURCE_NAME=CP.IDTabStrom+N'|'+CP.Pracoviste+ISNULL(N'|'+CS.Kod,''), 
  BATCH_TYPE_ID=CKS.KodSdruzeni 
FROM (SELECT DISTINCT PLANNED_BATCH_ID FROM hvw_APSLogis_IN_MFGORDEROPER) X 
  INNER JOIN TabSdruzVyrOperace SO ON (SO.ID=convert(int,SUBSTRING(X.PLANNED_BATCH_ID,2,10))) 
  INNER JOIN TabCisKoduSdruzeni CKS ON (CKS.ID=SO.IDKoduSdruzeni) 
  INNER JOIN TabCPraco CP ON (CP.ID=SO.IDPracoviste) 
  LEFT OUTER JOIN TabCisStroju CS ON (CS.ID=SO.IDStroje) 
GO

