USE [RayService]
GO

/****** Object:  View [dbo].[hvw_Tabx_RS_OUT_MANUFACTURORDERJAG_h]    Script Date: 04.07.2025 8:44:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_Tabx_RS_OUT_MANUFACTURORDERJAG_h] AS SELECT*FROM Tabx_RS_OUT_MANUFACTURINGORDERJAGGING_hist
GO

