USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_OUT_MFGORDEROPER]    Script Date: 03.07.2025 13:29:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_OUT_MFGORDEROPER] AS SELECT * FROM GTabAPSLogis_OUT_MFGORDEROPERATION
GO

