USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_IN_ROUTINGHEADER]    Script Date: 03.07.2025 13:06:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_IN_ROUTINGHEADER] AS SELECT DISTINCT 
  ROUTING_NAME=ROUTING_NAME, 
  Description=ROUTING_NAME 
FROM hvw_APSLogis_IN_ROUTINGOPERATION 
GO

