USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_IN_BOMHEADER]    Script Date: 03.07.2025 12:52:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_IN_BOMHEADER] AS SELECT DISTINCT 
  BOM_ID=BOM_ID, 
  USAGE_DESCRIPTION=BOM_ID 
FROM hvw_APSLogis_IN_BOMCOMPONENT 
GO

