USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_OUT_PURCHASEORDER]    Script Date: 03.07.2025 13:33:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_OUT_PURCHASEORDER] AS SELECT X.*, 
       RAY_IM_TotalConsumptions=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_TotalConsumptions'), 
       RAY_IM_TotalPOSupplies=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_TotalPOSupplies'), 
       RAY_IM_TotalPOPSupplies=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_TotalPOPSupplies'), 
       RAY_PotvrzenyTDOD=(SELECT TOP 1 P.DATE_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_PotvrzenyTDOD'), 
       RAY_Zamestnanec=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_Zamestnanec'), 
       RAY_IM_InitialStock=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_InitialStock'), 
       RAY_IM_FinalStock=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPERTY P WHERE P.PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_FinalStock') 
  FROM GTabAPSLogis_OUT_PURCHASEORDER X 
GO

