USE [RayService]
GO

/****** Object:  View [dbo].[hvw_Tabx_RS_OUT_MFGORDERKAMING]    Script Date: 04.07.2025 8:45:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_Tabx_RS_OUT_MFGORDERKAMING] AS SELECT*FROM Tabx_RS_OUT_MANUFACTURINGORDERKAMING
GO

