USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_IN_PURCHASEORDERPRO]    Script Date: 03.07.2025 13:05:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_IN_PURCHASEORDERPRO] AS SELECT 
  PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID, 
  ATTRIBUTE_NAME=N'RAY_Zamestnanec', 
  STRING_VALUE=ISNULL(CZ.PrijmeniJmeno, CO_E._odpovednaOsobaOdberatel), 
  NUMERIC_VALUE=NULL, 
  BOOL_VALUE=NULL 
FROM hvw_APSLogis_IN_PURCHASEORDER X 
  INNER JOIN TabDokladyZbozi DZ ON (DZ.ID=X.IDHeKey_H) 
  LEFT OUTER JOIN TabCisZam CZ ON (CZ.Cislo=DZ.CisloZam) 
  LEFT OUTER JOIN TabCisOrg CO ON (CO.CisloOrg=X.SUPPLIER_ID) 
  LEFT OUTER JOIN TabCisOrg_Ext CO_E ON (CO_E.ID=CO.ID) 
WHERE LEN(ISNULL(CZ.PrijmeniJmeno, CO_E._odpovednaOsobaOdberatel))>0 
UNION ALL 
SELECT 
  PURCHASE_ORDER_ID=X.PURCHASE_ORDER_ID, 
  ATTRIBUTE_NAME=N'RAY_PotvrzenyTDOD', 
  STRING_VALUE=NULL, 
  NUMERIC_VALUE=NULL, 
  BOOL_VALUE=1 
FROM hvw_APSLogis_IN_PURCHASEORDER X 
  INNER JOIN TabPohybyZbozi PZ ON (PZ.ID=X.IDHeKey_P) 
WHERE PZ.PotvrzDatDod IS NOT NULL 
GO

