USE [RayService]
GO

/****** Object:  View [dbo].[hvw_8E876DD0D46D4AE7A27836E9DA14F92E]    Script Date: 03.07.2025 12:33:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_8E876DD0D46D4AE7A27836E9DA14F92E] AS SELECT [ID]
      ,[IDZakazka]
      ,[IDFinal]
      ,[IDKalkVzor]
      ,[Strom]
      ,[Patro]
      ,[IDVyssi]
      ,[TypRadku]
      ,[IDVazby]
      ,[PopisRadku]
      ,[mnf]
      ,[Mnozstvi]
      ,[mat]
      ,[matA]
      ,[matB]
      ,[matC]
      ,[MatRezie]
      ,[koop]
      ,[TAC]
      ,[TAC_T]
      ,[TBC]
      ,[TBC_T]
      ,[TEC]
      ,[TEC_T]
      ,[TAC_Obsluhy]
      ,[TAC_Obsluhy_T]
      ,[TBC_Obsluhy]
      ,[TBC_Obsluhy_T]
      ,[TEC_Obsluhy]
      ,[TEC_Obsluhy_T]
      ,[TAC_KC]
      ,[TBC_KC]
      ,[TEC_KC]
      ,[rezieS]
      ,[rezieP]
      ,[ReziePrac]
      ,[NakladyPrac]
      ,[OPN]
      ,[VedProdukt]
      ,[Naradi]
      ,[TAC_S]
      ,[TAC_N]
      ,[TAC_H]
      ,[TBC_S]
      ,[TBC_N]
      ,[TBC_H]
      ,[TEC_S]
      ,[TEC_N]
      ,[TEC_H]
      ,[TAC_Obsluhy_S]
      ,[TAC_Obsluhy_N]
      ,[TAC_Obsluhy_H]
      ,[TBC_Obsluhy_S]
      ,[TBC_Obsluhy_N]
      ,[TBC_Obsluhy_H]
      ,[TEC_Obsluhy_S]
      ,[TEC_Obsluhy_N]
      ,[TEC_Obsluhy_H]
      ,[CenaCelkem]
      ,[JNmat]
      ,[JNmatA]
      ,[JNmatB]
      ,[JNmatC]
      ,[JNMatRezie]
      ,[JNkoop]
      ,[JNTAC_KC]
      ,[JNTBC_KC]
      ,[JNTEC_KC]
      ,[JNrezieS]
      ,[JNrezieP]
      ,[JNReziePrac]
      ,[JNNakladyPrac]
      ,[JNOPN]
      ,[JNVedProdukt]
      ,[JNnaradi]
      ,[JNCelkem]
      ,[Autor]
      ,[Prime]
      ,[Date_calc]
      ,[IDNizsi]
  FROM TabDetailniKalkulace_kalk WITH(NOLOCK)
GO

