USE [RayService]
GO

/****** Object:  View [dbo].[hvw_OUT_RESOURCECALENDAREXP]    Script Date: 03.07.2025 15:30:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_OUT_RESOURCECALENDAREXP] AS SELECT *,
DATEPART(YEAR,END_TIME) AS END_TIME_Y,
DATEPART(MONTH,END_TIME) AS END_TIME_M,
DATEPART(WEEK,END_TIME) AS END_TIME_W
FROM LADB.dbo.OUT_RESOURCECALENDAREXP
GO

