USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_OUT_PURCHASEORDPROP]    Script Date: 03.07.2025 13:34:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_OUT_PURCHASEORDPROP] AS SELECT X.*, 
       RAY_IM_FinalStock=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_FinalStock'), 
       RAY_demand_order_ids=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_demand_order_ids'), 
       RAY_IM_TotalConsumptions=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_TotalConsumptions'), 
       RAY_IM_TotalPOPSupplies=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_TotalPOPSupplies'), 
       RAY_IM_TotalPOSupplies=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_TotalPOSupplies'), 
       RAY_IM_InitialStock=(SELECT TOP 1 P.NUMERIC_VALUE FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_IM_InitialStock'), 
       RAY_RadaPlanu=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSALPROP P WHERE P.PROPOSAL_ID=X.PROPOSAL_ID AND P.ATTRIBUTE_NAME=N'RAY_RadaPlanu') 
  FROM GTabAPSLogis_OUT_PURCHASEORDERPROPOSAL X 
GO

