USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_OUT_MANUFACORDER]    Script Date: 03.07.2025 13:28:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_OUT_MANUFACORDER] AS SELECT X.*, 
  Prop_CisloZakazky=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_ZakazkaID'), 
  Prop_RadaVP=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_RadaVP'), 
  Prop_Pokryto=ISNULL((SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_Potvrzeno'),0), 
  RAY_SkupinaPlanu=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_SkupinaPlanu'), 
  RAY_RadaPlanu=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_RadaPlanu'), 
  RAY_DokonceniProcesDilce=(SELECT TOP 1 P.DATE_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_DokonceniProcesDilce'), 
  RAY_FAIR=ISNULL((SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_FAIR'),0), 
  RAY_DeltaFair=ISNULL((SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_DeltaFair'),0), 
  RAY_FAIRint=ISNULL((SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_FAIRint'),0), 
  RAY_fair_not_required=ISNULL((SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_fair_not_required'),0), 
  RAY_vg_protokol=ISNULL((SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_vg_protokol'),0), 
  RAY_Rozpracovana_zmena=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_Rozpracovana_zmena'), 
  DEMAND_ORDER_IDS=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'DEMAND_ORDER_IDS'), 
  RAY_NazvyOrganizaci=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_NazvyOrganizaci'), 
  RAY_DO_SalesOrderID=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_DO_SalesOrderID'), 
  RAY_UrovenFAIR=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_MANUFACTURINGORDERPROPERTY P WHERE P.MFG_ORDER_ID=X.MFG_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_UrovenFAIR') 
  FROM GTabAPSLogis_OUT_MANUFACTURINGORDER X
GO

