USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_OUT_MFGORDERPEGGING]    Script Date: 03.07.2025 13:31:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_OUT_MFGORDERPEGGING] AS SELECT * FROM GTabAPSLogis_OUT_MFGORDERPEGGING
GO

