USE [RayService]
GO

/****** Object:  View [dbo].[hvw_APSLogis_OUT_DEMANDORDER]    Script Date: 03.07.2025 13:28:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[hvw_APSLogis_OUT_DEMANDORDER] AS SELECT X.*, 
       ObjVyrRozdil=DATEDIFF(day, X.PLANNED_COMPLETION_TIME, X.DUE_DATE), 
       RAY_StavZakazky=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_StavZakazky'), 
       RAY_FAIR=(SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_FAIR'), 
       RAY_vg_protokol=(SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_vg_protokol'), 
       RAY_SkupinaPlanu=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_SkupinaPlanu'), 
       RAY_fair_not_required=(SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_fair_not_required'), 
       RAY_DeltaFair=(SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_DeltaFair'), 
       RAY_RadaPlanu=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_RadaPlanu'), 
       RAY_FAIRint=(SELECT TOP 1 P.BOOL_VALUE FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_FAIRint'), 
       RAY_mfg_order_id=(SELECT TOP 1 P.STRING_VALUE_255 FROM GTabAPSLogis_OUT_DEMANDORDERPROPERTY P WHERE P.DEMAND_ORDER_ID=X.DEMAND_ORDER_ID AND P.ATTRIBUTE_NAME=N'RAY_mfg_order_id') 
  FROM GTabAPSLogis_OUT_DEMANDORDER X 
GO

