USE [RayService]
GO

/****** Object:  Table [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING]    Script Date: 02.07.2025 9:25:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEMAND_ID] [nvarchar](100) NOT NULL,
	[SUPPLY_ID] [nvarchar](4000) NULL,
	[QTY_ALLOCATED] [numeric](19, 6) NULL,
	[AVAILABLE_DATE] [datetime] NULL,
	[SUPPLY_TYPE] [nvarchar](100) NULL,
	[CisloZakazky] [nvarchar](15) NULL,
	[IDPohybu] [int] NULL,
	[SupplyTypeOrig] [int] NULL,
	[IDPrikaz] [int] NULL,
	[IDDoklad] [int] NULL,
	[Autor] [nvarchar](128) NOT NULL,
	[DatPorizeni] [datetime] NOT NULL,
	[Zmenil] [nvarchar](128) NULL,
	[DatZmeny] [datetime] NULL,
	[BlokovaniEditoru] [smallint] NULL,
	[DatPorizeni_D]  AS (datepart(day,[DatPorizeni])),
	[DatPorizeni_M]  AS (datepart(month,[DatPorizeni])),
	[DatPorizeni_Y]  AS (datepart(year,[DatPorizeni])),
	[DatPorizeni_Q]  AS (datepart(quarter,[DatPorizeni])),
	[DatPorizeni_W]  AS (datepart(week,[DatPorizeni])),
	[DatPorizeni_X]  AS (CONVERT([datetime],CONVERT([int],CONVERT([float],[DatPorizeni])))),
	[DatZmeny_D]  AS (datepart(day,[DatZmeny])),
	[DatZmeny_M]  AS (datepart(month,[DatZmeny])),
	[DatZmeny_Y]  AS (datepart(year,[DatZmeny])),
	[DatZmeny_Q]  AS (datepart(quarter,[DatZmeny])),
	[DatZmeny_W]  AS (datepart(week,[DatZmeny])),
	[DatZmeny_X]  AS (CONVERT([datetime],CONVERT([int],CONVERT([float],[DatZmeny])))),
 CONSTRAINT [PK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] ADD  CONSTRAINT [DF__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__QTY_ALLOCATED]  DEFAULT ((0)) FOR [QTY_ALLOCATED]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] ADD  CONSTRAINT [DF__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__Autor]  DEFAULT (suser_sname()) FOR [Autor]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] ADD  CONSTRAINT [DF__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__DatPorizeni]  DEFAULT (getdate()) FOR [DatPorizeni]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING]  WITH CHECK ADD  CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__CisloZakazky] FOREIGN KEY([CisloZakazky])
REFERENCES [dbo].[TabZakazka] ([CisloZakazky])
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] CHECK CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__CisloZakazky]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING]  WITH CHECK ADD  CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__IDDoklad] FOREIGN KEY([IDDoklad])
REFERENCES [dbo].[TabDokladyZbozi] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] CHECK CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__IDDoklad]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING]  WITH CHECK ADD  CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__IDPohybu] FOREIGN KEY([IDPohybu])
REFERENCES [dbo].[TabPohybyZbozi] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] CHECK CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__IDPohybu]
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING]  WITH CHECK ADD  CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__IDPrikaz] FOREIGN KEY([IDPrikaz])
REFERENCES [dbo].[TabPrikaz] ([ID])
GO

ALTER TABLE [dbo].[Tabx_RS_OUT_MANUFACTURINGORDERKAMING] CHECK CONSTRAINT [FK__Tabx_RS_OUT_MANUFACTURINGORDERKAMING__IDPrikaz]
GO

