USE [RayService]
GO

/****** Object:  Table [dbo].[Tabx_Hmotnost_Uprav]    Script Date: 02.07.2025 8:44:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tabx_Hmotnost_Uprav](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDKmen] [int] NOT NULL,
	[Hmotnost] [numeric](19, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

