USE [RayService]
GO

/****** Object:  Table [dbo].[Tabx_DruhDokZboImp]    Script Date: 02.07.2025 8:42:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tabx_DruhDokZboImp](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RadaDokladu] [nvarchar](3) NOT NULL,
	[NavaznaRada] [nvarchar](3) NULL,
	[NavaznyPohyb] [tinyint] NULL,
	[Nazev] [nvarchar](40) NOT NULL,
	[DruhPohybuZbo] [tinyint] NOT NULL,
	[PohybSkladu] [tinyint] NOT NULL,
	[UKod] [int] NULL,
	[PovolenyNuly] [nchar](1) NOT NULL,
	[TiskovyForm] [int] NULL,
	[InterniDoklad] [nchar](1) NOT NULL,
	[DruhMeny] [nvarchar](3) NULL,
	[VstupniCena] [tinyint] NOT NULL,
	[Poznamka] [ntext] NULL,
	[PosledniPC] [int] NOT NULL,
	[CisloZakazky] [nvarchar](15) NULL,
	[AutoRealizace] [tinyint] NOT NULL,
	[PovolenNovy] [nchar](1) NOT NULL,
	[FormaUhrady] [nvarchar](30) NULL,
	[Sleva] [numeric](5, 2) NOT NULL,
	[OdHodnoty] [numeric](19, 6) NOT NULL,
	[HlidaniDokladu] [nchar](1) NOT NULL,
	[PouzitOdhadZvyseniNC] [nchar](1) NOT NULL,
	[DefOKTisk] [bit] NOT NULL,
	[DefOKReal] [bit] NOT NULL,
	[DefOKUcto] [bit] NOT NULL,
	[DefOKNext] [bit] NOT NULL,
	[DefOKJCD] [bit] NOT NULL,
	[DefOKZJCD] [bit] NOT NULL,
	[DefOKExtA] [int] NULL,
	[TabExtKom_GUID] [binary](16) NULL,
	[DefOKExtARunPo] [int] NULL,
	[Pokladna] [nvarchar](3) NULL,
	[DodrzetShodnePorC] [bit] NOT NULL,
	[StredNaklad] [nvarchar](30) NULL,
	[NOkruh] [nvarchar](15) NULL,
	[IDVozidlo] [int] NULL,
	[TabIVozidlo_SPZZobraz] [nvarchar](12) NULL,
	[TabIVozidlo_EvCislo] [nvarchar](20) NULL,
	[OsvobozenaPlneni] [tinyint] NOT NULL,
	[DatumPokladny] [tinyint] NOT NULL,
	[DatumFaktury] [tinyint] NOT NULL,
	[DoplnkovyKod] [nvarchar](10) NULL,
	[UctoCislovani] [tinyint] NOT NULL,
	[FaNavCisloSkladu] [nvarchar](30) NULL,
	[KontrolaJakosti] [bit] NOT NULL,
	[VyrZaplZaloh] [bit] NOT NULL,
	[PrefixDodFak] [nvarchar](20) NOT NULL,
	[PrevodParam] [tinyint] NOT NULL,
	[TypPrevodky] [nvarchar](3) NULL,
	[IDSkladPrevodu] [nvarchar](30) NULL,
	[TabDruhDZ_DruhPohybuZboPre] [tinyint] NULL,
	[ZPZ] [nvarchar](2) NULL,
	[ZPZtext] [nvarchar](40) NOT NULL,
	[ZemeUrceni] [nvarchar](2) NOT NULL,
	[Region] [tinyint] NULL,
	[DodaciPodminky] [nvarchar](3) NOT NULL,
	[DD] [tinyint] NULL,
	[PovahaTransakce] [tinyint] NULL,
	[DoPenTok] [bit] NOT NULL,
	[DefOKVyznamOK] [int] NOT NULL,
	[DefOKAutomat] [int] NULL,
	[TabAutomatPoradac_GUID] [binary](16) NULL,
	[TabAutomatPrehled_Poradi] [int] NULL,
	[ZadavaniOkruhu] [tinyint] NOT NULL,
	[ZadavaniAuta] [tinyint] NOT NULL,
	[ZadavaniZakazka] [tinyint] NOT NULL,
	[ZadavaniStrediska] [tinyint] NOT NULL,
	[NavaznyDruhPrevodu] [tinyint] NOT NULL,
	[TextPokladny] [int] NOT NULL,
	[VlastniTextPokladny] [nvarchar](255) NULL,
	[CisZam] [int] NULL,
	[ZadavaniZamestnance] [tinyint] NOT NULL,
	[UKodPokladny] [int] NULL,
	[ParZnakPokladny] [int] NOT NULL,
	[PredAnal] [bit] NOT NULL,
	[SazbaDPH] [numeric](5, 2) NULL,
	[PlneniPoznamkyPD] [tinyint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

