USE [RayService]
GO

/****** Object:  Table [dbo].[Tabx_RS_TabPrKVazby]    Script Date: 02.07.2025 9:55:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tabx_RS_TabPrKVazby](
	[ID] [int] NULL,
	[Doklad] [int] NULL,
	[IDPrikaz] [int] NULL,
	[Prednastaveno] [bit] NULL,
	[predzpracovano] [bit] NULL,
	[Sklad] [nvarchar](30) NULL,
	[VyrStredisko] [nvarchar](30) NULL,
	[IDPracoviste] [int] NULL,
	[mnoz_zad] [numeric](19, 6) NULL,
	[Mnoz_nepotrebne] [numeric](19, 6) NULL,
	[Mnoz_skut_realizovane] [numeric](19, 6) NULL,
	[Mnoz_odv] [numeric](19, 6) NULL,
	[Uzavreno] [bit] NULL,
	[AutorUzavreni] [nvarchar](128) NULL,
	[IDOdchylkyOd] [int] NULL,
	[IDOdchylkyDo] [int] NULL,
	[priorita] [int] NULL,
	[vyssi] [int] NULL,
	[nizsi] [int] NULL,
	[pozice] [nvarchar](100) NULL,
	[Operace] [nchar](4) NULL,
	[mnozstvi] [numeric](19, 6) NULL,
	[ProcZtrat] [numeric](5, 2) NULL,
	[Prirez] [numeric](19, 6) NULL,
	[Poznamka] [ntext] NULL,
	[DatPorizeni] [datetime] NULL,
	[Autor] [nvarchar](128) NULL,
	[Zmenil] [nvarchar](128) NULL,
	[DatZmeny] [datetime] NULL,
	[BlokovaniEditoru] [smallint] NULL,
	[ID1] [int] NULL,
	[RefMnoz] [numeric](19, 6) NULL,
	[VydanoRefMnoz] [numeric](19, 6) NULL,
	[mnozstviSeZtratou] [numeric](19, 6) NULL,
	[IDVzorceSpotMat] [int] NULL,
	[PromA] [numeric](19, 6) NULL,
	[PromB] [numeric](19, 6) NULL,
	[PromC] [numeric](19, 6) NULL,
	[PromD] [numeric](19, 6) NULL,
	[PromE] [numeric](19, 6) NULL,
	[SpotRozmer] [nvarchar](100) NULL,
	[mat_real] [numeric](19, 6) NULL,
	[mat_odv] [numeric](19, 6) NULL,
	[MatRezie_real] [numeric](19, 6) NULL,
	[koop_real] [numeric](19, 6) NULL,
	[mzda_real] [numeric](19, 6) NULL,
	[rezieS_real] [numeric](19, 6) NULL,
	[rezieP_real] [numeric](19, 6) NULL,
	[ReziePrac_real] [numeric](19, 6) NULL,
	[NakladyPrac_real] [numeric](19, 6) NULL,
	[OPN_real] [numeric](19, 6) NULL,
	[VedProdukt_real] [numeric](19, 6) NULL,
	[naradi_real] [numeric](19, 6) NULL,
	[NespecNakl_real] [numeric](19, 6) NULL,
	[MatRezie_odv] [numeric](19, 6) NULL,
	[koop_odv] [numeric](19, 6) NULL,
	[mzda_odv] [numeric](19, 6) NULL,
	[rezieS_odv] [numeric](19, 6) NULL,
	[rezieP_odv] [numeric](19, 6) NULL,
	[ReziePrac_odv] [numeric](19, 6) NULL,
	[NakladyPrac_odv] [numeric](19, 6) NULL,
	[OPN_odv] [numeric](19, 6) NULL,
	[VedProdukt_odv] [numeric](19, 6) NULL,
	[naradi_odv] [numeric](19, 6) NULL,
	[NespecNakl_odv] [numeric](19, 6) NULL,
	[FixniMnozstvi] [numeric](19, 6) NULL,
	[AutorTisku] [nvarchar](128) NULL,
	[DatumTisku] [datetime] NULL,
	[DavkaTPV] [numeric](19, 6) NULL,
	[Cena_real] [numeric](19, 6) NULL,
	[Cena_odv] [numeric](19, 6) NULL,
	[Odchylkovano] [bit] NULL,
	[DatPorizeni_D] [int] NULL,
	[DatPorizeni_M] [int] NULL,
	[DatPorizeni_Y] [int] NULL,
	[DatPorizeni_Q] [int] NULL,
	[DatPorizeni_W] [int] NULL,
	[DatPorizeni_X] [int] NULL,
	[DatZmeny_D] [int] NULL,
	[DatZmeny_M] [int] NULL,
	[DatZmeny_Y] [int] NULL,
	[DatZmeny_Q] [int] NULL,
	[DatZmeny_W] [int] NULL,
	[DatZmeny_X] [int] NULL,
	[Vytisteno] [bit] NULL,
	[DatumTisku_D] [int] NULL,
	[DatumTisku_M] [int] NULL,
	[DatumTisku_Y] [int] NULL,
	[DatumTisku_Q] [int] NULL,
	[DatumTisku_W] [int] NULL,
	[DatumTisku_X] [int] NULL,
	[LastRecord] [tinyint] NULL,
	[RezijniMat] [bit] NULL,
	[VyraditZKalkulace] [bit] NULL,
	[JeNeco_real] [bit] NULL,
	[JeNeco_NeOdv] [bit] NULL,
	[mnoz_pozadovane] [numeric](19, 6) NULL,
	[matA_real] [numeric](19, 6) NULL,
	[matB_real] [numeric](19, 6) NULL,
	[matC_real] [numeric](19, 6) NULL,
	[matA_odv] [numeric](19, 6) NULL,
	[matB_odv] [numeric](19, 6) NULL,
	[matC_odv] [numeric](19, 6) NULL,
	[mnoz_Nevydane] [numeric](19, 6) NULL,
	[Splneno] [bit] NULL,
	[ProcSplneni] [numeric](19, 6) NULL,
	[VychoziSklad] [nvarchar](30) NULL,
	[UzivNastSklad] [bit] NULL,
	[UzivZadaniPrirezu] [bit] NULL,
	[Ident] [int] NULL,
	[CPrirez] [numeric](19, 6) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

